### ISSUE TITLE
[DISCUSS] [DSL] help command keyword

### ISSUE THREAD

**Issue by cfmcgrady** [byzer-org/byzer-lang#545]
`load` and `train` is using for train algthrim model and prepare data processing. 
```sql
load modelExample.`modelName` as tableName; `
```
and
```sql
load modelParams.`modelName` as tableName; `
```
is not make sense.
i think a batter idea is use `show` or `usaege` keyword.

**Comment by allwefantasy** [comment]
Use `show`  or `usage` will introduce new keywords.  Too many keywords may increase the difficulty of learning. I hope 

```
load 
select
train/run
register
set
include
```

will cover most usage scene.

The second reason we use load is that we hope users should at least  master load statement since load statement is the first step when they write MLSQL script.
