### ISSUE TITLE
sparkSession.newSession(): Can't inherit Root SparkSession's UDF and temporary tables.

### ISSUE THREAD

**Issue by latincross** [byzer-org/byzer-lang#671]
When the rest service is invoked and sessionPerUser equals to true, a new SparkSession will be created from Root SparkSession， but it can't inherit Root SparkSession's UDF and temporary tables.

**Comment by allwefantasy** [comment]
In MLSQL, there is always have a Root SparkSession, and any SparkSession belongs to a specific user should be created from the root SparkSession. 

We hope they inherit the UDF/Temporary tables from Root SparkSession.
However, we should also provide user the control by startup-config or request parameters. 

We will try to fix this in MLSQL-1.1.5 since MLSQL 1.1.4 will be freed the next week.
